title:       Blog
name:        Blog
author:      Laurent 
url:         https://blog.ghirardotti.fr
description: Migration du Tumblr

theme: jekyll-theme-hacker

paginate: 4

gems:
  - jekyll-sitemap
  - jekyll-paginate
  
